Temporarily skip DB migration tests
The DB migration tests are failing with:
AssertionError: backend 'postgresql' unavailable

Until we fix this issue, we need to skip those tests

Change-Id: If8519efda40978e5e6d2ada73f2254af4990bb4e