Squash two patches below to make pep8 & unit tests pass again
We were really unlucky that both of these broke at the sametime.

Patch # 1

Bugfix: Add translation hints

Recent pep8's are failing due to a few missing translation
hints on log messages.

Authored-By: Boden R <bodenvmw@gmail.com>

Patch # 2

Add netifaces to test-requirements.txt

The oslo util devs moved netifaces dependencies to extras. As
a result all the projects should install it separately by having
it in their test-requirements.txt
https://github.com/openstack/oslo.utils/commit/2abbe1c3b19490f570c29502cd56ec92daf4ca45#comments

This was also causing our gate to fail,
ImportError: No module named netifaces

This would fix it.

launchpad bug: https://bugs.launchpad.net/oslo.utils/+bug/1523706

Change-Id: I9dfec9570e2d569d6f12bf3cc3b60144846d87ab
Authored-By: Akash Gangil<gangila@vmware.com>