Test: Use Network OVO in db_base_plugin
Running locally with the depends on patch, UTs fail with errors like:

AttributeError: 'Network' object has no attribute 'qos_queue'

This patch tests the functional and other jobs to see what results
we get. Likely we'll need to do some work in order for vmware-nsx
to work with network OVOs.

Depends-On: https://review.openstack.org/#/c/507772/
Change-Id: Ie2a6696ce83781838f7fa998b7f4f91af0579497