Add netifaces to test-requirements.txt
The oslo util devs moved netifaces dependencies to extras. As
a result all the projects should install it separately by having
it in their test-requirements.txt
https://github.com/openstack/oslo.utils/commit/2abbe1c3b19490f570c29502cd56ec92daf4ca45#comments

This was also causing our gate to fail,
ImportError: No module named netifaces

This would fix it.

launchpad bug: https://bugs.launchpad.net/oslo.utils/+bug/1523706

Change-Id: I4023e7c727d88e7fc14e99940c7e4ed861d2a2e1